### ISSUE TITLE
EventOutputFormat

### ISSUE THREAD

**Issue by vincentrussell** [calrissian/accumulo-recipes#355]
It would be nice to have an EventOutputFormat to be able to write to the EventStore via map reduce.

**Comment by eawagner** [comment]
This should probably also be done for the EntityStore which is effectively the same thing

**Comment by vincentrussell** [comment]
Ok.. thanks for the feedback.. I'll take a look.

**Comment by eawagner** [comment]
+1

**Comment by vincentrussell** [comment]
same as #271
