### ISSUE TITLE
update accumulo version to 1.8

### ISSUE THREAD

**Issue by vincentrussell** [calrissian/accumulo-recipes#362]
currently it's set at 1.6.1.

**Comment by eawagner** [comment]
+1 

One benefit to upgrading to atleast 1.7 is that the QFD stores (Entity, Event, Graph) can take advantage of the new group tablet balancer. It is very useful for helping to spread out shards evenly.

Also 1.8 has the iterator test harness which would be nice for testing out the iterators.  I know I had come across a few bugs in the boolean logic iterators which theoretically could have been caught by the test harness.
