### ISSUE TITLE
javadocs need to be fixed

### ISSUE THREAD

**Issue by vincentrussell** [calrissian/accumulo-recipes#365]
@cjnolet @eawagner the javadocs need to be fixed to fix the complication issues?  How do you want approach this?  I am not sure I know enough about the API to fix them myself.

**Comment by eawagner** [comment]
I would just add <additionalparam>-Xdoclint:none</additionalparam> to the javadoc parameters.  

The issue is because you are using jdk8 to compile.  If we add this we might want to change the java target to 1.8 also.

**Comment by vincentrussell** [comment]
oh ok.   awesome.. I'll try that and i'll close this issue.  I guess we'll also want to change this on travis.

Thanks,
